/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/backend/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get proxy backend capability information. */
        get: operations["get_backend_capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current application configuration. */
        get: operations["get_config"];
        /** Update the application configuration. */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint. */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hwid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current device HWID and device information. */
        get: operations["get_hwid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hwid/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Regenerate the device HWID. */
        put: operations["regenerate_hwid"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all proxy nodes, optionally filtered by subscription. */
        get: operations["list_nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a node as the selected/active node. */
        put: operations["select_node"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proxy/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the proxy for a node. */
        post: operations["start_proxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proxy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current proxy process status. */
        get: operations["get_proxy_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proxy/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the proxy process. */
        post: operations["stop_proxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/split-tunnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List split tunnel rules, optionally filtered by node. */
        get: operations["list_split_tunnel_rules"];
        put?: never;
        /** Add a new split tunnel rule. */
        post: operations["create_split_tunnel_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/split-tunnel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single split tunnel rule. */
        get: operations["get_split_tunnel_rule"];
        /** Update a split tunnel rule. */
        put: operations["update_split_tunnel_rule"];
        post?: never;
        /** Delete a split tunnel rule. */
        delete: operations["delete_split_tunnel_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all stored subscriptions. */
        get: operations["list_subscriptions"];
        put?: never;
        /** Add a new subscription. */
        post: operations["create_subscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single subscription with its nodes. */
        get: operations["get_subscription"];
        put?: never;
        post?: never;
        /** Delete a subscription. */
        delete: operations["delete_subscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Fetch/reload a subscription from its source URL. */
        put: operations["fetch_subscription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for adding a split tunnel rule. */
        AddSplitTunnelRuleRequest: {
            action: components["schemas"]["SplitTunnelAction"];
            /** Format: uuid */
            node_id?: string | null;
            target: components["schemas"]["SplitTunnelTarget"];
            value: string;
        };
        /** @description Request body for adding a subscription. */
        AddSubscriptionRequest: {
            hwid?: string | null;
            name?: string | null;
            url: string;
        };
        /** @description Top-level application configuration. */
        AppConfig: {
            general?: components["schemas"]["GeneralConfig"];
            hwid?: components["schemas"]["HwidConfig"];
            logging?: components["schemas"]["LoggingConfig"];
            subscription?: components["schemas"]["SubscriptionConfig"];
        };
        /** @description Capabilities reported by the daemon for the installed proxy cores. */
        BackendCapabilities: {
            sing_box: components["schemas"]["BackendCapability"];
            xray: components["schemas"]["BackendCapability"];
        };
        /** @description Capabilities for a single proxy core backend. */
        BackendCapability: {
            available: boolean;
            geo_assets_available: boolean;
            version?: string | null;
        };
        /**
         * @description User-selectable backend type.
         * @enum {string}
         */
        BackendType: "auto" | "sing_box" | "xray";
        /** @description Config response wrapping the existing application config. */
        ConfigResponse: {
            config: components["schemas"]["AppConfig"];
        };
        /** @description General application settings. */
        GeneralConfig: {
            /** Format: int32 */
            max_retries?: number;
            /** Format: int64 */
            timeout_secs?: number;
            user_agent?: string;
        };
        /** @description Aggregate health/status response. */
        HealthResponse: {
            hwid: string;
            status: string;
            /** Format: int64 */
            uptime_secs: number;
            version: string;
        };
        /** @description HWID generation settings. */
        HwidConfig: {
            custom_id?: string | null;
            device_model_override?: string | null;
            enabled?: boolean;
        };
        /** @description Hardware/device identifier information. */
        HwidInfo: {
            device_model: string;
            hostname: string;
            hwid: string;
            machine_id: string;
            os: string;
            username: string;
        };
        /** @description HWID response. */
        HwidResponse: {
            hwid: string;
            info: components["schemas"]["HwidInfo"];
        };
        /** @description Logging settings. */
        LoggingConfig: {
            file?: boolean;
            level?: string;
            /**
             * Format: path
             * @description Path to the directory containing log files.
             */
            log_dir?: string | null;
        };
        /** @description A node with its owning subscription context. */
        NodeWithSubscription: {
            /** Format: uuid */
            id: string;
            node: components["schemas"]["ProxyNode"];
            selected?: boolean;
            /** Format: uuid */
            subscription_id: string;
            subscription_name?: string | null;
        };
        /**
         * @description Network protocol used by a proxy node.
         * @enum {string}
         */
        Protocol: "vless" | "vmess" | "trojan" | "shadowsocks" | "hysteria2" | "tuic" | "wire_guard" | "any_tls";
        /** @description A parsed proxy node from a subscription. */
        ProxyNode: {
            alpn?: string[] | null;
            /** Format: int32 */
            alter_id?: number | null;
            encryption?: string | null;
            extra?: null | components["schemas"]["XhttpExtra"];
            fingerprint?: string | null;
            flow?: string | null;
            host?: string | null;
            name: string;
            password?: string | null;
            path?: string | null;
            /** Format: int32 */
            port: number;
            protocol: components["schemas"]["Protocol"];
            public_key?: string | null;
            raw_uri: string;
            security: components["schemas"]["Security"];
            server: string;
            service_name?: string | null;
            short_id?: string | null;
            sni?: string | null;
            spider_x?: string | null;
            tags: string[];
            transport: components["schemas"]["Transport"];
            uuid?: string | null;
        };
        /** @description Response body for proxy status. */
        ProxyStatus: {
            backend?: null | components["schemas"]["BackendType"];
            /** Format: int32 */
            http_port?: number | null;
            last_error?: string | null;
            /** Format: int32 */
            mixed_port?: number | null;
            /** Format: int32 */
            pid?: number | null;
            running: boolean;
            selected_node?: null | components["schemas"]["NodeWithSubscription"];
            /** Format: int32 */
            socks_port?: number | null;
            /** Format: int64 */
            uptime_secs?: number | null;
        };
        /**
         * @description Security layer used by a proxy node.
         * @enum {string}
         */
        Security: "none" | "tls" | "reality" | "reality_psk";
        /**
         * @description Action for a split tunnel rule.
         * @enum {string}
         */
        SplitTunnelAction: "direct" | "proxy";
        /** @description A user-defined split tunnel (selective routing) rule. */
        SplitTunnelRule: {
            action: components["schemas"]["SplitTunnelAction"];
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            node_id?: string | null;
            target: components["schemas"]["SplitTunnelTarget"];
            /** Format: date-time */
            updated_at: string;
            value: string;
        };
        /**
         * @description Target type for a split tunnel rule.
         * @enum {string}
         */
        SplitTunnelTarget: "domain" | "ip" | "cidr" | "app";
        /** @description Request body for starting the proxy. */
        StartProxyRequest: {
            backend?: null | components["schemas"]["BackendType"];
            /** Format: int32 */
            http_port?: number | null;
            /** Format: int32 */
            mixed_port?: number | null;
            /** Format: uuid */
            node_id?: string | null;
            /** Format: int32 */
            socks_port?: number | null;
        };
        /** @description Stored subscription record with cached nodes and metadata. */
        StoredSubscription: {
            /** Format: date-time */
            added_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            hwid?: string | null;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            /** Format: date-time */
            last_updated?: string | null;
            metadata: components["schemas"]["SubscriptionMetadata"];
            name?: string | null;
            /** Format: int64 */
            traffic_total?: number | null;
            /** Format: int64 */
            traffic_used?: number | null;
            url: string;
        };
        /** @description Subscription fetching settings. */
        SubscriptionConfig: {
            auto_update?: boolean;
            extra_headers?: {
                [key: string]: string;
            };
            proxy?: string | null;
            /** Format: int64 */
            update_interval_hours?: number;
        };
        /** @description Detailed subscription response including its nodes. */
        SubscriptionDetail: {
            nodes: components["schemas"]["NodeWithSubscription"][];
            subscription: components["schemas"]["StoredSubscription"];
        };
        /**
         * @description Provider-specific metadata extracted from subscription headers or inline body lines.
         *
         *     The fetcher recognises the de-facto standard keys used by many providers:
         *     `profile-title`, `profile-update-interval`, `profile-web-page-url` and
         *     `announce`/`announces`. Values prefixed with `base64:` are decoded
         *     automatically. HTTP response headers take precedence over inline body values.
         */
        SubscriptionMetadata: {
            /** @description Provider announcement or status message. */
            announcement?: string | null;
            /** @description Raw map of all recognised header keys and their (decoded) values. */
            headers: {
                [key: string]: string;
            };
            /** @description Human-readable profile title, if provided. */
            profile_title?: string | null;
            /**
             * Format: int64
             * @description Recommended update interval in hours.
             */
            profile_update_interval_hours?: number | null;
            /** @description Provider web page or support URL. */
            profile_web_page_url?: string | null;
        };
        /**
         * @description Transport layer used by a proxy node.
         * @enum {string}
         */
        Transport: "tcp" | "ws" | "grpc" | "h2" | "xhttp" | "splithttp" | "kcp";
        /** @description Request body for updating a split tunnel rule. */
        UpdateSplitTunnelRuleRequest: {
            action: components["schemas"]["SplitTunnelAction"];
            /** Format: uuid */
            node_id?: string | null;
            target: components["schemas"]["SplitTunnelTarget"];
            value: string;
        };
        /** @description XHTTP transport extra settings carried in the `extra` query parameter. */
        XhttpExtra: {
            /** @description Optional request headers merged into the HTTP upgrade request. */
            headers?: {
                [key: string]: string;
            };
            /**
             * Format: int64
             * @description HTTP/2 ` SETTINGS_MAX_CONCURRENT_STREAMS` hint (used for HTTP/2 mode).
             */
            maxConcurrentUploads?: number | null;
            /**
             * Format: int64
             * @description Maximum number of upstream sessions kept open (HTTP/2 mode).
             */
            maxConnections?: number | null;
            /** @description XHTTP operating mode, e.g. `stream-up` or `packet-up`. */
            mode?: string | null;
            /** @description `stream-up` submode: `"raw"` or `"packet-up"`. */
            noGrpcHeader?: boolean | null;
            /** @description Optional padding range for the HTTP request body, e.g. `"100-1000"`. */
            xPaddingBytes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_backend_capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendCapabilities"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfig"];
            };
        };
        responses: {
            /** @description Updated config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Invalid configuration */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_hwid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HWID and device info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HwidResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regenerate_hwid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regenerated HWID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HwidResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_nodes: {
        parameters: {
            query?: {
                /** @description Optional subscription ID filter */
                subscription?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeWithSubscription"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    select_node: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node selected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeWithSubscription"];
                };
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_proxy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartProxyRequest"];
            };
        };
        responses: {
            /** @description Proxy started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyStatus"];
                };
            };
            /** @description No node selected or unsupported node/backend */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Node not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_proxy_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyStatus"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stop_proxy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyStatus"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_split_tunnel_rules: {
        parameters: {
            query?: {
                /** @description Optional node ID filter */
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitTunnelRule"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_split_tunnel_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSplitTunnelRuleRequest"];
            };
        };
        responses: {
            /** @description Rule created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitTunnelRule"];
                };
            };
            /** @description Invalid rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_split_tunnel_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitTunnelRule"];
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_split_tunnel_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSplitTunnelRuleRequest"];
            };
        };
        responses: {
            /** @description Rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitTunnelRule"];
                };
            };
            /** @description Invalid rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_split_tunnel_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_subscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSubscription"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredSubscription"];
                };
            };
            /** @description Invalid request or duplicate subscription */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDetail"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_subscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fetch_subscription: {
        parameters: {
            query?: {
                /** @description Optional HWID override */
                hwid?: string;
            };
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDetail"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
