use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use ironpass_core::models::{HwidInfo, Protocol};
use ironpass_core::traits::{HwidProvider, SubscriptionFetcher};
use ironpass_subscription::{FetchOptions, HttpSubscriptionFetcher};
use mockall::mock;
use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use wiremock::matchers::{header, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

fn real_node_body() -> String {
    "vless://550e8400-e29b-41d4-a716-446655440001@example.org:443?encryption=none&security=tls&sni=example.org#RealNode".to_string()
}

fn placeholder_body() -> String {
    "vless://00000000-0000-0000-0000-000000000000@0.0.0.0:1?encryption=none#Placeholder".to_string()
}

fn base64_of(body: &str) -> String {
    STANDARD.encode(body.as_bytes())
}

mock! {
    HwidProvider {}

    impl HwidProvider for HwidProvider {
        fn generate(&self) -> ironpass_core::Result<String>;
        fn get_device_info(&self) -> ironpass_core::Result<HwidInfo>;
    }
}

fn fake_hwid_provider() -> (MockHwidProvider, HwidInfo) {
    let info = HwidInfo {
        hwid: "deadbeef".to_string(),
        device_model: "TestModel".to_string(),
        os: "TestOS (1.2.3)".to_string(),
        hostname: "testhost".to_string(),
        username: "testuser".to_string(),
        machine_id: "machine-id".to_string(),
    };
    let mut provider = MockHwidProvider::new();
    provider
        .expect_generate()
        .returning(|| Ok("autogenerated-hwid".to_string()));
    provider.expect_get_device_info().returning(move || {
        Ok(HwidInfo {
            hwid: "deadbeef".to_string(),
            device_model: "TestModel".to_string(),
            os: "TestOS (1.2.3)".to_string(),
            hostname: "testhost".to_string(),
            username: "testuser".to_string(),
            machine_id: "machine-id".to_string(),
        })
    });
    (provider, info)
}

#[tokio::test]
async fn auto_retries_with_generated_hwid_on_placeholder_response() {
    let server = MockServer::start().await;
    let counter = Arc::new(AtomicUsize::new(0));
    let counter_clone = counter.clone();

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(move |request: &wiremock::Request| {
            let n = counter_clone.fetch_add(1, Ordering::SeqCst);
            let has_hwid = request.headers.get("x-hwid").is_some();
            if n == 0 && !has_hwid {
                ResponseTemplate::new(200)
                    .insert_header("x-hwid-active", "true")
                    .insert_header("x-hwid-not-supported", "true")
                    .insert_header("x-hwid-limit", "true")
                    .set_body_string(base64_of(&placeholder_body()))
            } else if has_hwid {
                ResponseTemplate::new(200)
                    .insert_header("subscription-userinfo", "upload=1073741824; download=2147483648; total=10737418240; expire=1893456000")
                    .set_body_string(base64_of(&real_node_body()))
            } else {
                ResponseTemplate::new(500)
            }
        })
        .expect(2)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(sub.nodes.len(), 1);
    assert_eq!(sub.nodes[0].protocol, Protocol::Vless);
    assert_eq!(sub.nodes[0].server, "example.org");
    assert_eq!(sub.traffic_used, Some(3221225472));
    assert_eq!(sub.traffic_total, Some(10737418240));
}

#[tokio::test]
async fn returns_error_when_hwid_retry_still_yields_placeholders() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("x-hwid-active", "true")
                .insert_header("x-hwid-not-supported", "true")
                .insert_header("x-hwid-limit", "true")
                .set_body_string(base64_of(&placeholder_body())),
        )
        .expect(2)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions::default(),
    );

    let err = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap_err();

    let msg = format!("{}", err);
    assert!(
        msg.contains("placeholder") || msg.contains("HWID") || msg.contains("Device limit"),
        "unexpected error message: {}",
        msg
    );
}

#[tokio::test]
async fn returns_device_limit_error_when_hwid_limit_header_set() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("x-hwid-limit", "true")
                .set_body_string(base64_of(&placeholder_body())),
        )
        .expect(2)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions::default(),
    );

    let err = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap_err();

    assert!(
        matches!(err, ironpass_core::Error::DeviceLimitExceeded { .. }),
        "expected DeviceLimitExceeded, got {:?}",
        err
    );
}

#[tokio::test]
async fn does_not_auto_retry_when_disabled() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("x-hwid-active", "true")
                .insert_header("x-hwid-not-supported", "true")
                .set_body_string(base64_of(&placeholder_body())),
        )
        .expect(1)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions {
            auto_hwid_retry: false,
            max_hwid_retries: 1,
        },
    );

    let err = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap_err();

    let msg = format!("{}", err);
    assert!(
        msg.contains("placeholder") || msg.contains("HWID"),
        "unexpected error message: {}",
        msg
    );
}

#[tokio::test]
async fn sends_hwid_headers_when_hwid_supplied() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .and(header("x-hwid", "manual-hwid"))
        .and(header("x-device-model", "TestModel"))
        .and(header("x-device-os", "TestOS"))
        .and(header("x-ver-os", "TestOS (1.2.3)"))
        .and(header("User-Agent", "IronPass/0.1.0 (TestOS)"))
        .respond_with(ResponseTemplate::new(200).set_body_string(base64_of(&real_node_body())))
        .expect(1)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), Some("manual-hwid"))
        .await
        .unwrap();

    assert_eq!(sub.nodes.len(), 1);
}

#[tokio::test]
async fn uses_client_user_agent_without_hwid() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .and(header("User-Agent", "IronPass/0.1.0"))
        .respond_with(ResponseTemplate::new(200).set_body_string(base64_of(&real_node_body())))
        .expect(1)
        .mount(&server)
        .await;

    let (provider, _info) = fake_hwid_provider();
    let client = reqwest::Client::builder()
        .user_agent("IronPass/0.1.0")
        .build()
        .unwrap();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(provider),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(sub.nodes.len(), 1);
}
