use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use ironpass_core::models::{HwidInfo, Protocol};
use ironpass_core::traits::{HwidProvider, SubscriptionFetcher};
use ironpass_subscription::{FetchOptions, HttpSubscriptionFetcher};
use mockall::mock;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

fn real_node_body() -> String {
    "vless://550e8400-e29b-41d4-a716-446655440001@example.org:443?encryption=none&security=tls&sni=example.org#RealNode".to_string()
}

fn base64_of(body: &str) -> String {
    STANDARD.encode(body.as_bytes())
}

mock! {
    HwidProvider {}

    impl HwidProvider for HwidProvider {
        fn generate(&self) -> ironpass_core::Result<String>;
        fn get_device_info(&self) -> ironpass_core::Result<HwidInfo>;
    }
}

fn fake_hwid_provider() -> MockHwidProvider {
    let mut provider = MockHwidProvider::new();
    provider
        .expect_generate()
        .returning(|| Ok("autogenerated-hwid".to_string()));
    provider.expect_get_device_info().returning(|| {
        Ok(HwidInfo {
            hwid: "deadbeef".to_string(),
            device_model: "TestModel".to_string(),
            os: "TestOS (1.2.3)".to_string(),
            hostname: "testhost".to_string(),
            username: "testuser".to_string(),
            machine_id: "machine-id".to_string(),
        })
    });
    provider
}

#[tokio::test]
async fn extracts_metadata_from_http_headers() {
    let server = MockServer::start().await;
    let title_b64 = format!("base64:{}", STANDARD.encode("OutlineKeys".as_bytes()));
    let announce_b64 = format!("base64:{}", STANDARD.encode("HWID activation required".as_bytes()));

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("subscription-userinfo", "upload=0; download=205542220; total=322122547200; expire=1786355700")
                .insert_header("profile-title", &title_b64)
                .insert_header("profile-update-interval", "10")
                .insert_header("profile-web-page-url", "https://example.com/sub/TOKEN")
                .insert_header("announce", &announce_b64)
                .set_body_string(base64_of(&real_node_body())),
        )
        .expect(1)
        .mount(&server)
        .await;

    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(fake_hwid_provider()),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(sub.traffic_used, Some(205542220));
    assert_eq!(sub.traffic_total, Some(322122547200));
    assert!(sub.expires_at.is_some());

    assert_eq!(sub.metadata.profile_title.as_deref(), Some("OutlineKeys"));
    assert_eq!(sub.metadata.profile_update_interval_hours, Some(10));
    assert_eq!(
        sub.metadata.profile_web_page_url.as_deref(),
        Some("https://example.com/sub/TOKEN")
    );
    assert_eq!(
        sub.metadata.announcement.as_deref(),
        Some("HWID activation required")
    );
    assert_eq!(
        sub.metadata.headers.get("profile-update-interval"),
        Some(&"10".to_string())
    );
}

#[tokio::test]
async fn extracts_metadata_from_inline_body() {
    let server = MockServer::start().await;
    let announce_b64 = format!("base64:{}", STANDARD.encode("Inline announcement".as_bytes()));
    let body = format!(
        "profile-title=InlineTitle\nprofile-update-interval=24\nprofile-web-page-url=https://example.com/sub/TOKEN\nannounce={}\n{}",
        announce_b64,
        real_node_body()
    );

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(ResponseTemplate::new(200).set_body_string(base64_of(&body)))
        .expect(1)
        .mount(&server)
        .await;

    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(fake_hwid_provider()),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(sub.metadata.profile_title.as_deref(), Some("InlineTitle"));
    assert_eq!(sub.metadata.profile_update_interval_hours, Some(24));
    assert_eq!(
        sub.metadata.profile_web_page_url.as_deref(),
        Some("https://example.com/sub/TOKEN")
    );
    assert_eq!(
        sub.metadata.announcement.as_deref(),
        Some("Inline announcement")
    );
}

#[tokio::test]
async fn headers_take_precedence_over_inline_body_metadata() {
    let server = MockServer::start().await;
    let title_b64 = format!("base64:{}", STANDARD.encode("HeaderTitle".as_bytes()));
    let body = "profile-title=InlineTitle\nprofile-update-interval=42\n";
    let full_body = format!("{}\n{}", body, real_node_body());

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("profile-title", &title_b64)
                .insert_header("profile-update-interval", "12")
                .set_body_string(base64_of(&full_body)),
        )
        .expect(1)
        .mount(&server)
        .await;

    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(fake_hwid_provider()),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(sub.metadata.profile_title.as_deref(), Some("HeaderTitle"));
    assert_eq!(sub.metadata.profile_update_interval_hours, Some(12));
}

#[tokio::test]
async fn body_metadata_used_when_headers_absent() {
    let server = MockServer::start().await;
    let body = "profile-title=FallbackTitle\nannounces=FallbackAnnounce\n";
    let full_body = format!("{}\n{}", body, real_node_body());

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(ResponseTemplate::new(200).set_body_string(base64_of(&full_body)))
        .expect(1)
        .mount(&server)
        .await;

    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(fake_hwid_provider()),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert_eq!(
        sub.metadata.profile_title.as_deref(),
        Some("FallbackTitle")
    );
    assert_eq!(
        sub.metadata.announcement.as_deref(),
        Some("FallbackAnnounce")
    );
}

#[tokio::test]
async fn leaves_metadata_empty_when_no_headers_or_inline_values() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/sub/TOKEN"))
        .respond_with(ResponseTemplate::new(200).set_body_string(base64_of(&real_node_body())))
        .expect(1)
        .mount(&server)
        .await;

    let client = reqwest::Client::new();
    let fetcher = HttpSubscriptionFetcher::with_client_and_provider(
        client,
        Box::new(fake_hwid_provider()),
        FetchOptions::default(),
    );

    let sub = fetcher
        .fetch(&format!("{}/sub/TOKEN", server.uri()), None)
        .await
        .unwrap();

    assert!(sub.metadata.profile_title.is_none());
    assert!(sub.metadata.profile_update_interval_hours.is_none());
    assert!(sub.metadata.profile_web_page_url.is_none());
    assert!(sub.metadata.announcement.is_none());
    assert!(sub.metadata.headers.is_empty());
    assert_eq!(sub.nodes[0].protocol, Protocol::Vless);
}
