[package]
name = "ironpass-engine"
description = "Proxy engine — VLESS/Trojan client, SOCKS5 server, TUN split tunneling"
version.workspace = true
edition.workspace = true

[dependencies]
ironpass-core = { workspace = true }
tokio = { workspace = true }
bytes = "1"
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
x25519-dalek = { workspace = true }
aes-gcm = { workspace = true }
chacha20poly1305 = { workspace = true }
h2 = { workspace = true }
tungstenite = { workspace = true }
tokio-tungstenite = { workspace = true }
prost = { workspace = true }
trust-dns-resolver = { workspace = true }
socket2 = { workspace = true }
tun = { workspace = true }
etherparse = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
hmac = "0.13"
pbkdf2 = { version = "0.13", features = ["hmac"] }
aes = "0.9"
cipher = "0.5"
rand_core = "0.10"
ring = "0.17"
webpki = { version = "0.22", features = ["std"] }
webpki-roots = "1.0"
tokio-rustls = "0.26"
hex = "0.4"
http = "1"
http-body-util = "0.1"
futures-core = "0.3"
futures-util = "0.3"
